# Generated by Django 3.2.5 on 2024-08-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0009_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
