# Generated by Django 3.2.5 on 2024-08-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0015_auto_20240822_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cAnmerkung',
            field=models.TextField(blank=True, null=True),
        ),
    ]
