# Generated by Django 3.2.5 on 2024-08-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0017_customer_customer_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comments',
        ),
    ]
