# Generated by Django 3.2.5 on 2024-08-26 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0018_remove_order_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cAnmerkung',
            new_name='comments',
        ),
    ]
