# Generated by Django 3.2.5 on 2024-08-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_analysis', '0019_rename_canmerkung_order_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_net_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
